
import type { FlashcardData } from './types';

// Helper function to capitalize words with more than 2 letters
const capitalizeText = (text: string): string => {
  return text.split(' ').map(word => {
    // Don't capitalize words with 2 or fewer letters (like "de", "c.", "a")
    if (word.length <= 2 || word.startsWith('(')) {
      return word;
    }
    return word.charAt(0).toUpperCase() + word.slice(1).toLowerCase();
  }).join(' ');
};

export const CARDS: FlashcardData[] = [
  { id: 1, front: capitalizeText("Coxinha"), back: "100" },
  { id: 2, front: capitalizeText("Bauru"), back: "108" },
  { id: 3, front: capitalizeText("PF"), back: "2" },
  { id: 4, front: capitalizeText("Cuscus, Arroz e Carne de Sol"), back: "141" },
  { id: 5, front: capitalizeText("Cuscus Arroz e Bife"), back: "142" },
  { id: 6, front: capitalizeText("Cuscus Arroz e Frango"), back: "145" },
  { id: 7, front: capitalizeText("Cuscus, Arroz e Costela"), back: "145" },
  { id: 8, front: capitalizeText("Cuscus, Arroz e Bode"), back: "299" },
  { id: 9, front: capitalizeText("Cuscus com Bode"), back: "298" },
  { id: 10, front: capitalizeText("Cuscus com Frango"), back: "148" },
  { id: 11, front: capitalizeText("Cuscus com Costela"), back: "407" },
  { id: 12, front: capitalizeText("Café com Leite"), back: "201" },
  { id: 13, front: capitalizeText("Café Grande"), back: "203" },
  { id: 14, front: capitalizeText("Empada"), back: "221" },
  { id: 15, front: capitalizeText("Tartalete"), back: "222" },
  { id: 16, front: capitalizeText("Esfirra"), back: "111" },
  { id: 17, front: capitalizeText("Pastel"), back: "103" },
  { id: 18, front: capitalizeText("Coxão"), back: "101" },
  { id: 19, front: capitalizeText("Coca Lata"), back: "50" },
  { id: 20, front: capitalizeText("Fanta Lata"), back: "49" },
  { id: 21, front: capitalizeText("Kuat Lata"), back: "46" },
  { id: 22, front: capitalizeText("Fanta Uva Lata"), back: "48" },
  { id: 23, front: capitalizeText("Coca de 500ml"), back: "57" },
  { id: 24, front: capitalizeText("Coca Pet de 1 LT"), back: "61" },
  { id: 25, front: capitalizeText("Coca LS de 1 Litro"), back: "68" },
  { id: 26, front: capitalizeText("Antarctica LS de 1 Litro"), back: "67" },
  { id: 27, front: capitalizeText("Fanta LS de 1 Litro"), back: "65" },
  { id: 28, front: capitalizeText("Coca Mini"), back: "223" },
  { id: 29, front: capitalizeText("Coco"), back: "99" },
  { id: 30, front: capitalizeText("Golito (Suco de Laranja Garrafa)"), back: "93" },
  { id: 31, front: capitalizeText("Café com Leite Grande (Copo Maior)"), back: "202" },
  { id: 32, front: capitalizeText("Panqueca"), back: "219" },
  { id: 33, front: capitalizeText("Enroladinho"), back: "262" },
  { id: 34, front: capitalizeText("Torta"), back: "106" },
  { id: 35, front: capitalizeText("Bolo"), back: "261" },
  { id: 36, front: capitalizeText("Copo de Leite"), back: "205" },
  { id: 37, front: capitalizeText("Água Mineral (P)"), back: "79" },
  { id: 38, front: capitalizeText("Água Mineral (G)"), back: "80" },
  { id: 39, front: capitalizeText("Água Mineral com Gás"), back: "81" },
  { id: 40, front: capitalizeText("Doce - Pudim"), back: "91" },
  { id: 41, front: capitalizeText("Cajuína"), back: "74" },
  { id: 42, front: capitalizeText("Sopa de Costela"), back: "116" },
  { id: 43, front: capitalizeText("Caldo de Costela"), back: "122" },
  { id: 44, front: capitalizeText("Caldo de Frango"), back: "124" },
  { id: 45, front: capitalizeText("Meio Caldo de Costela"), back: "123" },
  { id: 46, front: capitalizeText("Caldo de Carne Moída"), back: "126" },
  { id: 47, front: capitalizeText("Coca KS"), back: "53" },
  { id: 48, front: capitalizeText("Sprite Lata"), back: "47" },
  { id: 49, front: capitalizeText("Kuat 2 LT"), back: "78" },
  { id: 50, front: capitalizeText("Kuat Pet 500ml"), back: "59" },
  { id: 51, front: capitalizeText("Fanta Pet 500ml"), back: "58" },
  { id: 52, front: capitalizeText("Coca Lata Zero"), back: "51" },
  { id: 53, front: capitalizeText("Tônica (Schweppes)"), back: "52" },
  { id: 54, front: capitalizeText("Sprite Fresh"), back: "713" },
  { id: 55, front: capitalizeText("Fanta KS"), back: "54" },
  { id: 56, front: capitalizeText("Kuat KS"), back: "55" },
  { id: 57, front: capitalizeText("Meio Caldo de Carne Moída"), back: "127" },
  { id: 58, front: capitalizeText("Meio Caldo de Frango"), back: "125" },
  { id: 59, front: capitalizeText("Meio Caldo de Mocotó"), back: "272" },
  { id: 60, front: capitalizeText("Caldo de Mocotó"), back: "271" },
  { id: 61, front: capitalizeText("Toddynho"), back: "199" },
  { id: 62, front: capitalizeText("Pão c. Ovo"), back: "132" },
  { id: 156, front: capitalizeText("Porção de Macaxeira"), back: "156" },
  { id: 157, front: capitalizeText("Porção de Macarrão"), back: "157" },
  { id: 376, front: capitalizeText("Monster Energy"), back: "376" },
  { id: 88, front: capitalizeText("Red Bull"), back: "88" },
  { id: 408, front: capitalizeText("Megaton (P)"), back: "408" },
  { id: 86, front: capitalizeText("Power Bull 1 Litro"), back: "86" },
  { id: 90, front: capitalizeText("Guaraton"), back: "90" },
  { id: 409, front: capitalizeText("Megaton (G)"), back: "409" },
  { id: 110, front: capitalizeText("Pão de Queijo"), back: "110" },
  { id: 112, front: capitalizeText("Pão c. Queijo Coalho"), back: "112" },
  { id: 113, front: capitalizeText("Pão c. Queijo Manteiga"), back: "113" },
  { id: 258, front: capitalizeText("Pão Assado"), back: "258" },
  { id: 216, front: capitalizeText("Pão"), back: "216" },
  { id: 114, front: capitalizeText("Misto"), back: "114" },
  { id: 115, front: capitalizeText("Cachorro Quente"), back: "115" },
  { id: 130, front: capitalizeText("Pão c. Costela"), back: "130" },
  { id: 128, front: capitalizeText("Pão c. Bife"), back: "128" },
  { id: 129, front: capitalizeText("Pão c. Sol"), back: "129" },
  { id: 117, front: capitalizeText("Ovo"), back: "117" },
  { id: 170, front: capitalizeText("Queijo"), back: "170" },
  { id: 82, front: capitalizeText("Iogurte (G)"), back: "82" },
  { id: 84, front: capitalizeText("Iogurte (M)"), back: "84" },
  { id: 85, front: capitalizeText("Iogurte (P)"), back: "85" },
  { id: 172, front: capitalizeText("Suco de Caju"), back: "172" },
  { id: 267, front: capitalizeText("Suco de Acerola"), back: "267" },
  { id: 173, front: capitalizeText("Suco de Maracujá"), back: "173" },
  { id: 182, front: capitalizeText("Fandangos Presunto"), back: "182" },
  { id: 181, front: capitalizeText("Fandangos Queijo"), back: "181" },
  { id: 183, front: capitalizeText("Doritos"), back: "183" },
  { id: 179, front: capitalizeText("Cheetos Requeijão"), back: "179" },
  { id: 178, front: capitalizeText("Cheetos Lua"), back: "178" },
  { id: 180, front: capitalizeText("Cheetos Bola"), back: "180" },
  { id: 187, front: capitalizeText("Cebolitos"), back: "187" },
  { id: 190, front: capitalizeText("Batata Original 57G"), back: "190" },
  { id: 189, front: capitalizeText("Batata Churrasco 57G"), back: "189" },
  { id: 188, front: capitalizeText("Batata Cebola e Salsa 57G"), back: "188" },
  { id: 95, front: capitalizeText("Del Valle Citrus"), back: "95" },
  { id: 93, front: capitalizeText("Del Valle Uva"), back: "93" },
  { id: 405, front: capitalizeText("Macaxeira c. Sol"), back: "405" },
  { id: 135, front: capitalizeText("Macaxeira - Bife"), back: "135" },
  { id: 136, front: capitalizeText("Macaxeira c. Costela"), back: "136" },
  { id: 137, front: capitalizeText("Macaxeira c. Frango"), back: "137" },
  { id: 300, front: capitalizeText("Macaxeira c. Bode"), back: "300" },
  { id: 117, front: capitalizeText("Sopa de Frango"), back: "117" },
  { id: 118, front: capitalizeText("Sopa de Carne Moída"), back: "118" },
  { id: 119, front: capitalizeText("Meia Sopa Costela"), back: "119" },
  { id: 120, front: capitalizeText("Meia Sopa Frango"), back: "120" },
  { id: 121, front: capitalizeText("Meia Sopa c. Moída"), back: "121" },
  { id: 174, front: capitalizeText("Suco de Laranja"), back: "174" },
  { id: 175, front: capitalizeText("Jarra de Laranja"), back: "175" },
  { id: 155, front: capitalizeText("Porção de Cuscuz"), back: "155" },
  { id: 153, front: capitalizeText("Porção de Arroz"), back: "153" },
  { id: 154, front: capitalizeText("Porção de Feijão"), back: "154" },
  { id: 161, front: capitalizeText("Porção de Costela"), back: "161" },
  { id: 160, front: capitalizeText("Porção de Frango"), back: "160" },
  { id: 159, front: capitalizeText("Porção de Bife"), back: "159" },
  { id: 158, front: capitalizeText("Porção de Sol"), back: "158" },
];
